"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins as _builtins
import sys
import typing as _typing

from google.protobuf import descriptor as _descriptor
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _CancelRunAction:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType

class _CancelRunActionEnumTypeWrapper(
    _enum_type_wrapper._EnumTypeWrapper[_CancelRunAction.ValueType],
    _builtins.type,
):
    DESCRIPTOR: _descriptor.EnumDescriptor
    interrupt: _CancelRunAction.ValueType  # 0
    rollback: _CancelRunAction.ValueType  # 1

class CancelRunAction(_CancelRunAction, metaclass=_CancelRunActionEnumTypeWrapper): ...

interrupt: CancelRunAction.ValueType  # 0
rollback: CancelRunAction.ValueType  # 1
Global___CancelRunAction: _TypeAlias = CancelRunAction
