"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins as _builtins
import sys
import typing as _typing

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message

if sys.version_info >= (3, 11):
    from typing import Never as _Never
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import Never as _Never
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class UserCodeExecutionError(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_TYPE_FIELD_NUMBER: _builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: _builtins.int
    TRACEBACK_FIELD_NUMBER: _builtins.int
    error_type: _builtins.str
    error_message: _builtins.str
    traceback: _builtins.str
    def __init__(
        self,
        *,
        error_type: _builtins.str = ...,
        error_message: _builtins.str = ...,
        traceback: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "error_message",
        b"error_message",
        "error_type",
        b"error_type",
        "traceback",
        b"traceback",
    ]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UserCodeExecutionError: _TypeAlias = UserCodeExecutionError

@_typing.final
class GraphRecursionLimitError(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LIMIT_FIELD_NUMBER: _builtins.int
    limit: _builtins.int
    def __init__(
        self,
        *,
        limit: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["limit", b"limit"]
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GraphRecursionLimitError: _TypeAlias = GraphRecursionLimitError
