blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & discussion
    url: https://github.com/tam159/next-role/discussions
    about: Ask a question or discuss an idea (please don't open an issue for support).
